//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public int Cid { get; set; }
        public string Title { get; set; }
        public decimal ECTS { get; set; }
        public string Version { get; set; }
        public System.DateTime DateOfCreation { get; set; }

        public Courses()
        {
        }

        public Courses(int cid, string title, double ects, string version, DateTime dateOfCreation)
        {
            Cid = cid;
            Title = title;
            ECTS = Convert.ToDecimal(ects);
            Version = version;
            DateOfCreation = dateOfCreation;
        }

        public Courses(string title, double ects, string version, DateTime dateOfCreation)
        {
            Title = title;
            ECTS = Convert.ToDecimal(ects);
            Version = version;
            DateOfCreation = dateOfCreation;
        }
    }
}
